import React, { useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { usePets } from '../control/usePetControl';
import { analisarTriagem } from '../services/triagemService';

export default function TriagemScreen() {
  const pets = usePets();
  const [petId, setPetId] = useState<number | null>(null);
  const [sintomas, setSintomas] = useState({ vomito: false, diarreia: false, apatia: false, dificuldadeRespirar: false, observacoes: '' });
  const [resultado, setResultado] = useState<ReturnType<typeof analisarTriagem> | null>(null);
  const pet = useMemo(() => (pets.data || []).find((p) => p.id === petId), [pets.data, petId]);
  return <ScrollView style={styles.container}><Text style={styles.title}>Triagem de Risco</Text><Text style={styles.subtitle}>Selecione um pet e informe sintomas. A triagem não substitui avaliação veterinária.</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.pets}>{(pets.data || []).map((p) => <TouchableOpacity key={p.id} style={[styles.pet, petId === p.id && styles.petSelected]} onPress={() => setPetId(p.id)}><Text style={petId === p.id ? styles.petTextSelected : styles.petText}>{p.nome}</Text></TouchableOpacity>)}</ScrollView>{(['vomito','diarreia','apatia','dificuldadeRespirar'] as const).map((campo) => <View key={campo} style={styles.switchRow}><Text>{campo === 'dificuldadeRespirar' ? 'Dificuldade para respirar' : campo.charAt(0).toUpperCase() + campo.slice(1)}</Text><Switch value={sintomas[campo]} onValueChange={(v) => setSintomas({ ...sintomas, [campo]: v })} /></View>)}<TextInput style={styles.input} multiline placeholder="Observações" value={sintomas.observacoes} onChangeText={(v) => setSintomas({ ...sintomas, observacoes: v })} /><TouchableOpacity style={styles.button} onPress={() => setResultado(analisarTriagem(sintomas))}><Text style={styles.buttonText}>Analisar triagem</Text></TouchableOpacity>{resultado && <View style={styles.result}><Text style={styles.resultTitle}>{pet?.nome || 'Pet'} • {resultado.nivel}</Text><Text>{resultado.mensagem}</Text></View>}</ScrollView>;
}
const styles = StyleSheet.create({ container: { flex: 1, padding: 18, backgroundColor: '#f8fafc' }, title: { fontSize: 26, fontWeight: 'bold', color: '#1e293b' }, subtitle: { color: '#64748b', marginVertical: 10 }, pets: { maxHeight: 45, marginBottom: 12 }, pet: { paddingHorizontal: 12, paddingVertical: 8, borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 18, marginRight: 7, backgroundColor: '#fff' }, petSelected: { backgroundColor: '#2563eb' }, petText: { color: '#334155' }, petTextSelected: { color: '#fff', fontWeight: 'bold' }, switchRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#fff', padding: 12, borderRadius: 10, marginBottom: 8 }, input: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 8, padding: 12, minHeight: 80, marginVertical: 8 }, button: { backgroundColor: '#2563eb', padding: 13, borderRadius: 9 }, buttonText: { color: '#fff', textAlign: 'center', fontWeight: 'bold' }, result: { backgroundColor: '#fff', padding: 14, borderRadius: 10, borderWidth: 1, borderColor: '#e2e8f0', marginTop: 12 }, resultTitle: { fontWeight: 'bold', color: '#2563eb', marginBottom: 5 } });
